spring.application.name=bff-service
server.port=8080

# Datasource settings
spring.datasource.url=jdbc:postgresql://147.93.159.157:5432/iit_cw_sl
spring.datasource.username=iit
spring.datasource.password=iit@1
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# application.properties
debug=false

logging.level.root=INFO
logging.level.sun.rmi=OFF
logging.level.javax.management=OFF
logging.level.com.sun.jmx=OFF

spring.jmx.enabled=false

#Inter services
identity.service.url = http://localhost:9091