apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: data
type: Opaque
data:
  POSTGRES_DB: dGVjaHNhbGFyeQ==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
data:
  JWT_SECRET: ZGV2LXNlY3JldC1jaGFuZ2UtaW4tcHJvZA==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLmRhdGEuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi90ZWNoc2FsYXJ5